# Generated by Django 6.0.5 on 2026-05-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='civil_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='Civil ID / national ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.TextField(blank=True, help_text='Name, relationship, and phone number.', verbose_name='Emergency contact'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Employee ID / number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor'), ('intern', 'Intern')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('on_leave', 'On leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hierarchy.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Mobile number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='section_team',
            field=models.CharField(blank=True, max_length=120, verbose_name='Section / team'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
