# Generated by Django 6.0.5 on 2026-05-07 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_default_tenant(apps, schema_editor):
    Tenant = apps.get_model("hierarchy", "Tenant")
    TenantMembership = apps.get_model("hierarchy", "TenantMembership")
    User = apps.get_model("auth", "User")
    tenant, _ = Tenant.objects.get_or_create(
        slug="default",
        defaults={"name": "Default tenant", "is_active": True},
    )
    for user in User.objects.all():
        TenantMembership.objects.get_or_create(user=user, defaults={"tenant": tenant})


def reverse_assign_default_tenant(apps, schema_editor):
    TenantMembership = apps.get_model("hierarchy", "TenantMembership")
    TenantMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_employee_civil_id_employee_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='hierarchy.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tenant membership',
                'verbose_name_plural': 'tenant memberships',
            },
        ),
        migrations.RunPython(assign_default_tenant, reverse_assign_default_tenant),
    ]
