# Generated by Django 6.0.5 on 2026-05-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_tenant_api_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Short code for exports (optional).', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hierarchy.organizationalunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizational_units', to='hierarchy.tenant')),
            ],
            options={
                'verbose_name': 'organizational unit',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Job code or grade (optional).', max_length=64, verbose_name='Position code')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organizational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='hierarchy.organizationalunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hierarchy.tenant')),
            ],
            options={
                'ordering': ['organizational_unit_id', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='Marks the main role when someone holds several positions.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to='hierarchy.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hierarchy.position')),
            ],
            options={
                'ordering': ['-is_primary', '-start_date', 'pk'],
            },
        ),
    ]
