# Generated by Django 6.0.5 on 2026-05-07 19:28

import django.db.models.deletion
from django.db import migrations, models


def copy_membership_to_employee(apps, schema_editor):
    TenantMembership = apps.get_model("hierarchy", "TenantMembership")
    Employee = apps.get_model("hierarchy", "Employee")
    for m in TenantMembership.objects.all().iterator():
        try:
            emp = Employee.objects.get(user_id=m.user_id)
        except Employee.DoesNotExist:
            continue
        if emp.tenant_id != m.tenant_id:
            emp.tenant_id = m.tenant_id
            emp.save(update_fields=["tenant_id"])


def restore_membership_from_employee(apps, schema_editor):
    TenantMembership = apps.get_model("hierarchy", "TenantMembership")
    Employee = apps.get_model("hierarchy", "Employee")
    for emp in Employee.objects.exclude(tenant_id__isnull=True).iterator():
        TenantMembership.objects.update_or_create(
            user_id=emp.user_id,
            defaults={"tenant_id": emp.tenant_id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0005_organizational_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="hierarchy.tenant",
            ),
        ),
        migrations.RunPython(copy_membership_to_employee, restore_membership_from_employee),
        migrations.DeleteModel(
            name="TenantMembership",
        ),
    ]
