# Generated by Django 6.0.5 on 2026-05-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0006_employee_tenant_drop_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/%Y/%m/', verbose_name='Employee photo'),
        ),
    ]
