# Generated by Django 4.2.30 on 2026-05-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0009_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(blank=True, help_text='Shared secret for machine API clients (GET /api/employees/). Optional: override in production with env TENANT_API_KEY_<tenant_pk>.', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='api_key_header',
            field=models.CharField(blank=True, default='', help_text='HTTP header for api_key (default X-Api-Key if empty). Optional env: TENANT_API_KEY_HEADER_<tenant_pk>.', max_length=64),
        ),
    ]
