# Generated by Django 4.2.30 on 2026-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0014_organizationalunit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionassignment',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Legacy flag; each employee may only hold one current position.'),
        ),
    ]
