# Generated by Django 4.2.30 on 2026-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0016_orgunittypedefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionassignment',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Marks the main role when someone holds several positions.'),
        ),
    ]
