# Generated by Django 4.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0017_alter_positionassignment_is_primary"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegationTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes on when to use this pattern (e.g. acting director leave).",
                    ),
                ),
                (
                    "default_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        help_text="If set, new delegations from this template default end date to start + N days when end date is left blank.",
                    ),
                ),
                (
                    "default_is_full_substitute",
                    models.BooleanField(
                        default=True,
                        help_text="Full substitute delegations cannot overlap another full delegation from the same delegator.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in the “start from template” dropdown.",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegation_templates",
                        to="hierarchy.tenant",
                    ),
                ),
                (
                    "eligible_delegatee_positions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If any are selected, the delegatee must currently hold one of these positions. Empty means any employee in the tenant.",
                        related_name="delegation_templates_eligible",
                        to="hierarchy.position",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "delegation template",
            },
        ),
        migrations.AddConstraint(
            model_name="delegationtemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"),
                name="hierarchy_delegationtemplate_tenant_name_uniq",
            ),
        ),
        migrations.AddField(
            model_name="delegation",
            name="is_full_substitute",
            field=models.BooleanField(
                default=True,
                help_text="Full substitute: this person fully acts for the delegator. Only one overlapping full delegation per delegator is allowed.",
            ),
        ),
        migrations.AddField(
            model_name="delegation",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Pattern used when this delegation was created (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegations",
                to="hierarchy.delegationtemplate",
            ),
        ),
    ]
