# Generated by Django 4.2.30 on 2026-05-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0021_tenant_external_login_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegationtemplate',
            name='default_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='If set, applying this template fills end date as start + N days when end is left blank.', null=True),
        ),
        migrations.AlterField(
            model_name='delegationtemplate',
            name='default_is_full_substitute',
            field=models.BooleanField(default=True, help_text='Default for “full substitute” (overlapping full delegations per delegator are blocked).'),
        ),
        migrations.AlterField(
            model_name='delegationtemplate',
            name='eligible_delegatee_positions',
            field=models.ManyToManyField(blank=True, help_text='If any are selected, the delegatee must currently hold one of these positions. Leave empty to allow any employee in the tenant.', related_name='delegation_templates_eligible', to='hierarchy.position'),
        ),
        migrations.AlterField(
            model_name='positionassignment',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Main role when someone holds several positions; at most one assignment per employee may be primary.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='api_base_url',
            field=models.URLField(blank=True, help_text='External API: AD / Windows Authentication server this tenant uses. Scheme + host + port, e.g. http://63.183.213.237:1113. Hierarchy calls {base}/api/health and {base}/api/auth/users for sync and login.', max_length=500, verbose_name='External API (AD) base URL'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(blank=True, help_text='External API: secret sent to the AD server on outbound calls (stored on this tenant; not overridden by env).', max_length=255, verbose_name='ApiKey'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='api_key_header',
            field=models.CharField(blank=True, default='', help_text='External API: HTTP header name for ApiKey on AD requests; optional, defaults to X-Api-Key (tenant settings only).', max_length=64, verbose_name='ApiKeyHeader'),
        ),
    ]
