# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0022_alter_delegationtemplate_default_duration_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantApiUsageDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        help_text="Inbound: API route name. Outbound: health, ad_sync, ad_login.",
                        max_length=128,
                    ),
                ),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage_daily",
                        to="hierarchy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "tenant API usage (daily)",
                "verbose_name_plural": "tenant API usage (daily)",
                "ordering": ["-date", "direction", "operation"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "date"],
                        name="hierarchy_t_tenant__a1b2c3_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tenantapiusagedaily",
            constraint=models.UniqueConstraint(
                fields=("tenant", "date", "direction", "operation"),
                name="uniq_tenant_api_usage_daily",
            ),
        ),
    ]
