# Generated by Django 4.2.30 on 2026-05-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0023_tenant_api_usage_daily'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantapiusagedaily',
            new_name='hierarchy_t_tenant__9b8d71_idx',
            old_name='hierarchy_t_tenant__a1b2c3_idx',
        ),
        migrations.AlterField(
            model_name='tenantapiusagedaily',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
