"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5bb=z+(2fqe$e_515e%=fr(!az$r8%$4*fvm6ag&&vwae27dj2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hierarchy.apps.HierarchyConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'hierarchy.middleware.AuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hierarchy.context_processors.tenant_switcher',
                'hierarchy.context_processors.employee_photo_bar',
                'hierarchy.context_processors.directory_search_bar',
                'hierarchy.context_processors.staff_employee_profile_notice',
                'hierarchy.context_processors.tenant_api_types',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database: MySQL / MariaDB (HierarchyDB on remote host by default).
# Django 5+ requires MariaDB 10.6+; this stack uses Django 4.2 LTS for MariaDB 10.5.x.
# Upgrade MariaDB to 10.6+ if you want to move to Django 6.
#
# Set DJANGO_DB_PASSWORD (and optionally DJANGO_DB_HOST, DJANGO_DB_NAME, DJANGO_DB_USER, DJANGO_DB_PORT).
# Local SQLite: DJANGO_USE_SQLITE=1
#
# MySQL auth: If you see error 2059 (mysql_native_password plugin cannot be loaded), either:
#   • Use PyMySQL (default driver bootstrap below config/__init__.py): pip install PyMySQL
#   • Or on the server: ALTER USER ... IDENTIFIED WITH caching_sha2_password BY '...';
#   • Or force C mysqlclient: DJANGO_USE_MYSQLCLIENT=1 pip install mysqlclient
if os.environ.get("DJANGO_USE_SQLITE", "").lower() in ("1", "true", "yes"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("DJANGO_DB_NAME", "HierarchyDB"),
            "USER": os.environ.get("DJANGO_DB_USER", "remoteuser"),
            "PASSWORD": os.environ.get("DJANGO_DB_PASSWORD", "StrongPassword"),
            "HOST": os.environ.get("DJANGO_DB_HOST", "3.67.8.133"),
            "PORT": os.environ.get("DJANGO_DB_PORT", "3306"),
            "CONN_MAX_AGE": 60,
            "OPTIONS": {
                "init_command": (
                    "SET sql_mode='STRICT_TRANS_TABLES', "
                    "NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
                ),
                "charset": "utf8mb4",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# External API (AD) health probe fallback when a tenant has no api_base_url configured.
EXTERNAL_API_HEALTH_URL = os.environ.get(
    'EXTERNAL_API_HEALTH_URL',
    'http://63.183.213.237:1113/api/health',
)
EXTERNAL_API_HEALTH_TIMEOUT = int(os.environ.get('EXTERNAL_API_HEALTH_TIMEOUT', '10'))

# Optional global Bearer for ops only (leave unset in production; prefer per-tenant API keys).
EMPLOYEE_API_TOKEN = os.environ.get("EMPLOYEE_API_TOKEN", "").strip()
